### PR TITLE
AZP: update default test container version

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-807391460

### CODE REVIEW

**Comment by Andersson007** [comment]
04:36 ERROR: plugins/modules/hcloud_certificate.py:0:0: no-log-needed: Argument 'private_key' in argument_spec could be a secret, though doesn't have `no_log` set (0%)
04:36 ERROR: plugins/modules/hcloud_server.py:0:0: no-log-needed: Argument 'ssh_keys' in argument_spec could be a secret, though doesn't have `no_log` set (0%)

**Comment by Andersson007** [comment]
relaunch the tests here after https://github.com/ansible-collections/hetzner.hcloud/pull/70 is merged

**Comment by Andersson007** [comment]
cc @LKaemmerling

**Comment by LKaemmerling** [comment]
Yep thank you!

**Comment by Andersson007** [comment]
@LKaemmerling thanks!

**Pull request merged**
