### PR TITLE
[WIP] AZP fixes

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY
* As we only have a small number of sanity tests, don't group them
* Fix (or ignore) `shellcheck` errors.

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by LKaemmerling** [comment]
Hey @gundalow,

how is the state on this? We would have a few bugfixes that needs to be released :)

**Comment by dmsimard** [comment]
o/ @LKaemmerling

gundalow asked me to take a look, let me get back to you on that.

**Comment by dmsimard** [comment]
@LKaemmerling I think we should be good now -- shippable has been deactivated and azure pipelines are green.

Could you rebase your pull requests and let us know if there's anything ?

Thanks !

**Comment by LKaemmerling** [comment]
@dmsimard thank you! It looks like everything works fine now! cc @gundalow

**Pull request merged**
