### PR TITLE
Add possibility to specify private network when creating or updating servers

### LINKED ISSUE #150: Unable to create cloud server without public ipv4 and ipv6
##### SUMMARY
I am trying to create servers that is only connected to my private cloud network. I do not need a public IPv4 or IPv6 address.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hcloud_server

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
```

##### COLLECTION VERSION

```paste below
hetzner.hcloud    1.8.1
```

##### CONFIGURATION

```paste below
DEFAULT_ASK_PASS(ansible.cfg) = False
DEFAULT_ASK_VAULT_PASS(ansible.cfg) = True
DEFAULT_BECOME(ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(ansible.cfg) = False
DEFAULT_BECOME_METHOD(ansible.cfg) = sudo
DEFAULT_BECOME_USER(ansible.cfg) = root
DEFAULT_HOST_LIST(ansible.cfg) = ['/home/fgd/git/ex294_environment/inventory']
DEFAULT_KEEP_REMOTE_FILES(ansible.cfg) = False
DEFAULT_REMOTE_USER(ansible.cfg) = ansadm
DEPRECATION_WARNINGS(ansible.cfg) = False

```

##### OS / ENVIRONMENT

Linux rhelp 5.14.0-70.17.1.el9_0.aarch64 #1 SMP Tue Jun 14 11:43:56 EDT 2022 aarch64 aarch64 aarch64 GNU/Linux

##### STEPS TO REPRODUCE

Just try to create server with enable_ipv4 and enable_ipv6 to false.

```yaml

  - name: Provisioning Cloud server hetzner
    hetzner.hcloud.hcloud_server:
      api_token: "{{ hetzner_api_token }}"
      name: "{{ server }}"
      location: hel1
      image: fedora-36
      server_type: cx11
      backups: false
      delete_protection: false
      rebuild_protection: false
      enable_ipv4: false
      enable_ipv6: false
    loop: "{{ groups['cloudservers'] }}"
    loop_control:
      index_var: server
      pause: 2

```

##### EXPECTED RESULTS

That I should be able to add the private network I have defined instead.

##### ACTUAL RESULTS

The full traceback is:
  File "/tmp/ansible_hetzner.hcloud.hcloud_server_payload_n_pocdse/ansible_hetzner.hcloud.hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 438, in _create_server
  File "/home/fgd/.local/lib/python3.9/site-packages/hcloud/servers/client.py", line 583, in create
    response = self._client.request(url="/servers", method="POST", json=data)
  File "/home/fgd/.local/lib/python3.9/site-packages/hcloud/hcloud.py", line 242, in request
    self._raise_exception_from_json_content(json_content)
  File "/home/fgd/.local/lib/python3.9/site-packages/hcloud/hcloud.py", line 206, in _raise_exception_from_json_content
    raise APIException(
failed: [localhost] (item=ansible5.hl.local) => {
    "ansible_index_var": "server",
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_deprecated_image": false,
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "backups": false,
            "datacenter": null,
            "delete_protection": false,
            "enable_ipv4": false,
            "enable_ipv6": false,
            "endpoint": "https://api.hetzner.cloud/v1",
            "firewalls": null,
            "force": false,
            "force_upgrade": false,
            "id": null,
            "image": "fedora-36",
            "ipv4": null,
            "ipv6": null,
            "labels": null,
            "location": "hel1",
            "name": "4",
            "placement_group": null,
            "rebuild_protection": false,
            "rescue_mode": null,
            "server_type": "cx11",
            "ssh_keys": null,
            "state": "present",
            "upgrade_disk": false,
            "user_data": null,
            "volumes": null
        }
    },
    "item": "ansible5.hl.local",
    "msg": "invalid input: server must be attached to at least one of: primary_ipv4, primary_ipv6, private_network",
    "server": 4

```paste below

```

### PR DESCRIPTION
**Pull request by Galaxy102**
Hello, it's me again.
I'm opening this PR on behalf of the company I work for, Peerox GmbH.

Best regards,
Konstantin Köhring

##### SUMMARY
This fix allows creating servers without public internet access.
Previously this was impossible, because the API did not allow creating servers with neither public nor private networking, but the Ansible module did not allow specifying private networks when creating a server.

Fixes #150 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- hetzner.hcloud.server module
- hetzner.hcloud.server_info module

##### ADDITIONAL INFORMATION
1. Invoke the hetzner.hcloud.server module with the following data:
```
{
    "module_args": {
        "allow_deprecated_image": false,
        "api_token": "xxxx",
        "backups": null,
        "datacenter": null,
        "delete_protection": null,
        "enable_ipv4": false,
        "enable_ipv6": false,
        "endpoint": "https://api.hetzner.cloud/v1",
        "firewalls": null,
        "force": true,
        "force_upgrade": false,
        "id": null,
        "image": "ubuntu-22.04",
        "ipv4": null,
        "ipv6": null,
        "labels": null,
        "location": "fsn1",
        "name": "test-no-internet",
        "placement_group": null,
        "private_networks": [
            "my_network"
        ],
        "rebuild_protection": null,
        "rescue_mode": null,
        "server_type": "cx11",
        "ssh_keys": [
            "my_key"
        ],
        "state": "present",
        "upgrade_disk": false,
        "user_data": null,
        "volumes": null
    }
}
```

before:
```
{"msg": "invalid input: server must be attached to at least one of: primary_ipv4, primary_ipv6, private_network"}
```
after:
```
{
    "hcloud_server": {
        "backup_window": "None",
        "datacenter": "fsn1-dc14",
        "delete_protection": false,
        "id": "xxxx",
        "image": "ubuntu-22.04",
        "ipv4_address": null,
        "ipv6": null,
        "labels": {},
        "location": "fsn1",
        "name": "test-no-internet",
        "placement_group": null,
        "private_networks": [
            "my_network"
        ],
        "rebuild_protection": false,
        "rescue_enabled": false,
        "server_type": "cx11",
        "status": "running"
    }
}
```

### CODE REVIEW

**Comment by Galaxy102** [comment]
Sadly, the CI failed for an HTTP error when querying Ansible Galaxy (429 Too many requests). Could someone please look into it and retry the failed jobs?

**Comment by Galaxy102** [comment]
Sadly, a rebase didn't help to fix the Ansible Galaxy HTTP error. @LKaemmerling, as I've seen you're active today, could you please retry the pipeline?

**Comment by LKaemmerling** [comment]
Hey @Galaxy102,

thank you! Good job! Would it be possible that you add a test case as well [here](https://github.com/ansible-collections/hetzner.hcloud/tree/main/tests/integration/targets/hcloud_server/tasks)?

**Comment by LKaemmerling** [comment]
@Galaxy102 thank you! Great job!

**Review by LKaemmerling — APPROVED** [review]

**Pull request merged**
